# -*- coding: utf-8 -*-
"""PA02_CALIDAD DE VINOS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fgb9iw0Csnu8KbxpT58l3TQ6iRHz3NZZ

Data Set

Descripción:
El dataset Wine Quality contiene variables fisicoquímicas del vino como acidez, pH, alcohol, entre otras.
El objetivo es predecir la calidad del vino. En este caso, se transformará en un problema de clasificación donde se determinará si un vino es bueno o no
"""

Traer librerias a utilizar

import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, f1_score, classification_report

import joblib

"""Cargar la Data Set de github"""

url_red = "https://raw.githubusercontent.com/CeRo0007/wine-quality-ml/main/winequality-red.csv"

url_white = "https://raw.githubusercontent.com/CeRo0007/wine-quality-ml/main/winequality-white.csv"

# Cargar datasets
df_red = pd.read_csv(url_red, sep=';')
df_white = pd.read_csv(url_white, sep=';')

# Agregar tipo de vino
df_red['type'] = 'red'
df_white['type'] = 'white'

# Unir datasets
df = pd.concat([df_red, df_white], axis=0)

df.head()

"""Vista EDA"""

df.info()

df.shape

df.describe()

df.isnull().sum()

"""Graficas"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x='quality', data=df)

plt.title("Distribución de Calidad del Vino")
plt.xlabel("Calidad")
plt.ylabel("Cantidad")
plt.show()

"""La gráfica permite visualizar la frecuencia de cada nivel de calidad del vino,se puede observar que la mayoría de los vinos se concentran entre las calidades 5, 6 y 7, mientras que existen pocos vinos con calidades muy bajas o muy altas. La dataset presenta una mayor frecuencia de vinos de calidad media."""

# Correlación con la calidad
corr_quality = df.corr(numeric_only=True)['quality'] \
                  .sort_values(ascending=False)

# Mostrar correlaciones
print(corr_quality)
plt.figure(figsize=(10,6))

corr_quality.drop('quality').plot(
    kind='bar'
)

plt.title("Impacto de Variables en la Calidad del Vino")
plt.xlabel("Variables")
plt.ylabel("Correlación con Quality")

plt.show()

"""La gráfica muestra qué variables tienen mayor influencia sobre la calidad del vino según su nivel de correlación.
La variable alcohol presenta una correlación positiva más alta, lo que indica que vinos con mayor nivel de alcohol tienden a tener mejor calidad.
la variable acidez volátil presenta correlación negativa, lo que significa que niveles altos de esta característica pueden relacionarse con vinos de menor calidad.
"""

import pandas as pd

# URLs
url_red = "https://raw.githubusercontent.com/CeRo0007/wine-quality-ml/main/winequality-red.csv"

url_white = "https://raw.githubusercontent.com/CeRo0007/wine-quality-ml/main/winequality-white.csv"

# Cargar datasets
df_red = pd.read_csv(url_red, sep=';')
df_white = pd.read_csv(url_white, sep=';')

# Crear columna type
df_red['type'] = 'Red'
df_white['type'] = 'White'

# Unir datasets
df = pd.concat([df_red, df_white], axis=0)

# Verificar columnas
print(df.columns)

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x='type', data=df)

plt.title("Cantidad de Vinos por Tipo")
plt.xlabel("Tipo")
plt.ylabel("Cantidad")

plt.show()

"""Se observa que existe una mayor cantidad de vinos blancos en comparación con los vinos tintos.

Procesamiento de Datos

Conversión de la variable objetivo
Se transformará la variable quality en una clasificación binaria:
1 Vino de buena calidad
0 Vino de mala calidad
mayor o igual a 6 será de buena calidad
menor a 6 será de mala calidad
"""

# Crear variable binaria
df['quality_label'] = df['quality'].apply(
    lambda x: 1 if x >= 6 else 0
)

# Verificar resultados
df[['quality', 'quality_label']].head()

# Convertir variable categórica
df = pd.get_dummies(
    df,
    columns=['type'],
    drop_first=True
)

df.head()

"""Se obtiene las ariables predictoras y de objetivo"""

X = df.drop(
    ['quality', 'quality_label'],
    axis=1
)

# Variable objetivo
y = df['quality_label']

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X = scaler.fit_transform(X)

"""Explicación:
La variable quality fue transformada en una variable binaria quality_label para convertir el problema en clasificación.
La variable categórica type fue convertida a formato numérico mediante get_dummies.
Se aplicó escalado con StandardScaler para normalizar las variables y mejorar el rendimiento de modelos sensibles ante la magnitud en los datos
"""

PARTE 2
División de Datos

from sklearn.model_selection import train_test_split

# Variables predictoras
X = df.drop(['quality', 'quality_label'], axis=1)

# Variable objetivo
y = df['quality_label']

# División de datos
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Datos entrenamiento:", X_train.shape)
print("Datos prueba:", X_test.shape)

"""Se us+o train_test_split para dividir la dataset en datos de entrenamiento y prueba.
Se aplicó stratify=y para mantener la misma proporción de clases en ambos conjuntos de datos, evitando desbalance durante el entrenamiento del modelo

Entrenamiento de Modelos
"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

Modelo 1 Regresión logistica

from sklearn.linear_model import LogisticRegression

modelo_lr = LogisticRegression()

modelo_lr.fit(X_train, y_train)

"""Modelo 2 Random Forest"""

from sklearn.ensemble import RandomForestClassifier

modelo_rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

modelo_rf.fit(X_train, y_train)

"""Evaluación de Modelos"""

#Prediccion
pred_lr = modelo_lr.predict(X_test)
pred_rf = modelo_rf.predict(X_test)

"""Medidas"""

from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

print("LOGISTIC REGRESSION")

print("Accuracy:",
      accuracy_score(y_test, pred_lr))

print("F1 Score:",
      f1_score(y_test, pred_lr))

print("\n")

print("RANDOM FOREST")

print("Accuracy:",
      accuracy_score(y_test, pred_rf))

print("F1 Score:",
      f1_score(y_test, pred_rf))

"""El modelo de regresión logistica obtuvo buen nivel de precisión al clasificar la calidad de los vinos. El valor Accuracy indica el porcentaje de predicciones correctas realizadas por el modelo sobre el total de datos evaluados y F1 Score muestra el equilibrio entre precisión y recall, permitiendo evaluar qué tan bien el modelo identifica correctamente los vinos de buena y mala calidad.

En el modelo Random Forest tiene mayor capacidad para identificar patrones complejos y relaciones no lineales dentro de la dataset. El Accuracy refleja que el modelo realiza un alto porcentaje de predicciones correctas, mientras que el F1 Score demuestra un buen equilibrio entre precisión y recall al clasificar la calidad del vino

Debido a su mejor desempeño, Random Forest debe ser seleccionado como el modelo principal para el despliegue del proyecto.
"""

